//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagerLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderManagerLauncher.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot download update patch 的當地語系化字串。
        /// </summary>
        internal static string CannotDownloadOM {
            get {
                return ResourceManager.GetString("CannotDownloadOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot get update information 的當地語系化字串。
        /// </summary>
        internal static string CannotGetnewOMXML {
            get {
                return ResourceManager.GetString("CannotGetnewOMXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checking PrintIn Order version... 的當地語系化字串。
        /// </summary>
        internal static string CheckVersion {
            get {
                return ResourceManager.GetString("CheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 , please contact Inteware customer service 的當地語系化字串。
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading update pack... 的當地語系化字串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error occurred during data download 的當地語系化字串。
        /// </summary>
        internal static string DownloadingError {
            get {
                return ResourceManager.GetString("DownloadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error occurred during data unpack 的當地語系化字串。
        /// </summary>
        internal static string UnpackingError {
            get {
                return ResourceManager.GetString("UnpackingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Updating PrintIn Order ... 的當地語系化字串。
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
    }
}
