//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagerNew.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class HyperLink : global::System.Configuration.ApplicationSettingsBase {
        
        private static HyperLink defaultInstance = ((HyperLink)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HyperLink())));
        
        public static HyperLink Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.facebook.com/messages/t/484154545409477")]
        public string ContactInteware {
            get {
                return ((string)(this["ContactInteware"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://airdental.inteware.com.tw/findyouraccount/search")]
        public string ForgetAirdentalPassword {
            get {
                return ((string)(this["ForgetAirdentalPassword"]));
            }
        }
    }
}
