//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagerNew.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class OrderManagerProps : global::System.Configuration.ApplicationSettingsBase {
        
        private static OrderManagerProps defaultInstance = ((OrderManagerProps)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OrderManagerProps())));
        
        public static OrderManagerProps Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cad_projectDirectory {
            get {
                return ((string)(this["cad_projectDirectory"]));
            }
            set {
                this["cad_projectDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string implant_projectDirectory {
            get {
                return ((string)(this["implant_projectDirectory"]));
            }
            set {
                this["implant_projectDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ortho_projectDirectory {
            get {
                return ((string)(this["ortho_projectDirectory"]));
            }
            set {
                this["ortho_projectDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tray_projectDirectory {
            get {
                return ((string)(this["tray_projectDirectory"]));
            }
            set {
                this["tray_projectDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string splint_projectDirectory {
            get {
                return ((string)(this["splint_projectDirectory"]));
            }
            set {
                this["splint_projectDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DateFilter {
            get {
                return ((int)(this["DateFilter"]));
            }
            set {
                this["DateFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PatientNameFilter {
            get {
                return ((string)(this["PatientNameFilter"]));
            }
            set {
                this["PatientNameFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CaseNameFilter {
            get {
                return ((string)(this["CaseNameFilter"]));
            }
            set {
                this["CaseNameFilter"] = value;
            }
        }
    }
}
