//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagerNew.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderManagerNew.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 You are about to install  的當地語系化字串。
        /// </summary>
        internal static string AboutToInstall {
            get {
                return ResourceManager.GetString("AboutToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abutment 的當地語系化字串。
        /// </summary>
        internal static string Abutment {
            get {
                return ResourceManager.GetString("Abutment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abut. + Anatomic Coping 的當地語系化字串。
        /// </summary>
        internal static string Abutment___Anatomic_Coping {
            get {
                return ResourceManager.GetString("Abutment + Anatomic Coping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abut. + Anatomic Crown 的當地語系化字串。
        /// </summary>
        internal static string Abutment___Anatomic_Crown {
            get {
                return ResourceManager.GetString("Abutment + Anatomic Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abut. + Offset Coping 的當地語系化字串。
        /// </summary>
        internal static string Abutment___Offset_Coping {
            get {
                return ResourceManager.GetString("Abutment + Offset Coping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abut. + Temp Crown 的當地語系化字串。
        /// </summary>
        internal static string Abutment___Temp_Crown {
            get {
                return ResourceManager.GetString("Abutment + Temp Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Age 的當地語系化字串。
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ALL 的當地語系化字串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anatomic Coping 的當地語系化字串。
        /// </summary>
        internal static string Anatomic_Coping {
            get {
                return ResourceManager.GetString("Anatomic Coping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anatomic Coping (AI) 的當地語系化字串。
        /// </summary>
        internal static string Anatomic_Coping__AI_ {
            get {
                return ResourceManager.GetString("Anatomic Coping (AI)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anatomic Crown 的當地語系化字串。
        /// </summary>
        internal static string Anatomic_Crown {
            get {
                return ResourceManager.GetString("Anatomic Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anatomic Crown (AI) 的當地語系化字串。
        /// </summary>
        internal static string Anatomic_Crown__AI_ {
            get {
                return ResourceManager.GetString("Anatomic Crown (AI)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anatomic Crown Shell 的當地語系化字串。
        /// </summary>
        internal static string Anatomic_Crown_Shell {
            get {
                return ResourceManager.GetString("Anatomic Crown Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anatomic Pontic 的當地語系化字串。
        /// </summary>
        internal static string Anatomic_Pontic {
            get {
                return ResourceManager.GetString("Anatomic Pontic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to uninstall  的當地語系化字串。
        /// </summary>
        internal static string AreyousureUninstall {
            get {
                return ResourceManager.GetString("AreyousureUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Detect 的當地語系化字串。
        /// </summary>
        internal static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Brand 的當地語系化字串。
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Buy License 的當地語系化字串。
        /// </summary>
        internal static string BuyLic {
            get {
                return ResourceManager.GetString("BuyLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Case 的當地語系化字串。
        /// </summary>
        internal static string ByCase {
            get {
                return ResourceManager.GetString("ByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Date 的當地語系化字串。
        /// </summary>
        internal static string ByDate {
            get {
                return ResourceManager.GetString("ByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Patient 的當地語系化字串。
        /// </summary>
        internal static string ByPatient {
            get {
                return ResourceManager.GetString("ByPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Software 的當地語系化字串。
        /// </summary>
        internal static string BySoftware {
            get {
                return ResourceManager.GetString("BySoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose location for install: 的當地語系化字串。
        /// </summary>
        internal static string ChooseLocationToInstall {
            get {
                return ResourceManager.GetString("ChooseLocationToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear Aligner 的當地語系化字串。
        /// </summary>
        internal static string ClearAligner {
            get {
                return ResourceManager.GetString("ClearAligner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Client 的當地語系化字串。
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clinic 的當地語系化字串。
        /// </summary>
        internal static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string Close_titlebar {
            get {
                return ResourceManager.GetString("Close_titlebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contect Inteware 的當地語系化字串。
        /// </summary>
        internal static string Contect {
            get {
                return ResourceManager.GetString("Contect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Core Pontic 的當地語系化字串。
        /// </summary>
        internal static string Core_Pontic {
            get {
                return ResourceManager.GetString("Core Pontic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Date 的當地語系化字串。
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Order 的當地語系化字串。
        /// </summary>
        internal static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust Margin 的當地語系化字串。
        /// </summary>
        internal static string Crown_Margin_Adjust {
            get {
                return ResourceManager.GetString("Crown_Margin_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Post-Process 的當地語系化字串。
        /// </summary>
        internal static string Crown_Postprocess {
            get {
                return ResourceManager.GetString("Crown_Postprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Step:  的當地語系化字串。
        /// </summary>
        internal static string CurrentStep {
            get {
                return ResourceManager.GetString("CurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abutment Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_ABUTMENT {
            get {
                return ResourceManager.GetString("DDS_ABUTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cutback Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_ABUTMENT_CUTBACK {
            get {
                return ResourceManager.GetString("DDS_ABUTMENT_CUTBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deformation 的當地語系化字串。
        /// </summary>
        internal static string DDS_ABUTMENT_DEFORM {
            get {
                return ResourceManager.GetString("DDS_ABUTMENT_DEFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Screw Hole Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_ABUTMENT_SCREW {
            get {
                return ResourceManager.GetString("DDS_ABUTMENT_SCREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connector Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_CONNECTOR {
            get {
                return ResourceManager.GetString("DDS_CONNECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coping Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_COPING {
            get {
                return ResourceManager.GetString("DDS_COPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Crown Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_CROWN {
            get {
                return ResourceManager.GetString("DDS_CROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cutback Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_CURBACK {
            get {
                return ResourceManager.GetString("DDS_CURBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Crown Database 的當地語系化字串。
        /// </summary>
        internal static string DDS_CUSTOM_CROWN_DATABASE {
            get {
                return ResourceManager.GetString("DDS_CUSTOM_CROWN_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cutback Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_CUTBACK {
            get {
                return ResourceManager.GetString("DDS_CUTBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 eModel Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_EMODEL_MARGIN {
            get {
                return ResourceManager.GetString("DDS_EMODEL_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Final 的當地語系化字串。
        /// </summary>
        internal static string DDS_FINAL {
            get {
                return ResourceManager.GetString("DDS_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Design Parameter 的當地語系化字串。
        /// </summary>
        internal static string DDS_INNER {
            get {
                return ResourceManager.GetString("DDS_INNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insertion Operation 的當地語系化字串。
        /// </summary>
        internal static string DDS_INSERTION {
            get {
                return ResourceManager.GetString("DDS_INSERTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 jig Position 的當地語系化字串。
        /// </summary>
        internal static string DDS_JIG_POSITION {
            get {
                return ResourceManager.GetString("DDS_JIG_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Margin Operation 的當地語系化字串。
        /// </summary>
        internal static string DDS_MARGIN {
            get {
                return ResourceManager.GetString("DDS_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Crown Predesign 的當地語系化字串。
        /// </summary>
        internal static string DDS_PRECROWN {
            get {
                return ResourceManager.GetString("DDS_PRECROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Provisional Crown Design 的當地語系化字串。
        /// </summary>
        internal static string DDS_TEMPCROWN {
            get {
                return ResourceManager.GetString("DDS_TEMPCROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Occlusion 的當地語系化字串。
        /// </summary>
        internal static string DDS_ZAXIS {
            get {
                return ResourceManager.GetString("DDS_ZAXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Demo Case 的當地語系化字串。
        /// </summary>
        internal static string DemoCase {
            get {
                return ResourceManager.GetString("DemoCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dentist 的當地語系化字串。
        /// </summary>
        internal static string Dentist {
            get {
                return ResourceManager.GetString("Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Design Setting 的當地語系化字串。
        /// </summary>
        internal static string DesignSetting {
            get {
                return ResourceManager.GetString("DesignSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Design Step 的當地語系化字串。
        /// </summary>
        internal static string DesignStep {
            get {
                return ResourceManager.GetString("DesignStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Diagnostic Waxup Crown 的當地語系化字串。
        /// </summary>
        internal static string Diagnostic_Waxup_Crown {
            get {
                return ResourceManager.GetString("Diagnostic Waxup Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Diagnostic Waxup Pontic 的當地語系化字串。
        /// </summary>
        internal static string Diagnostic_Waxup_Pontic {
            get {
                return ResourceManager.GetString("Diagnostic Waxup Pontic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Directory 的當地語系化字串。
        /// </summary>
        internal static string Downloadpath {
            get {
                return ResourceManager.GetString("Downloadpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Software 的當地語系化字串。
        /// </summary>
        internal static string DownloadSoftware {
            get {
                return ResourceManager.GetString("DownloadSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 exePath conflict 的當地語系化字串。
        /// </summary>
        internal static string exePathConflict {
            get {
                return ResourceManager.GetString("exePathConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 exePath conflict, do you want to replace your exePath? 的當地語系化字串。
        /// </summary>
        internal static string exePathConflictDescription {
            get {
                return ResourceManager.GetString("exePathConflictDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Female 的當地語系化字串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Blockout 的當地語系化字串。
        /// </summary>
        internal static string GDS_BLOCKOUT {
            get {
                return ResourceManager.GetString("GDS_BLOCKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Splint Create 的當地語系化字串。
        /// </summary>
        internal static string GDS_GUIDECREATE_S {
            get {
                return ResourceManager.GetString("GDS_GUIDECREATE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tray Create 的當地語系化字串。
        /// </summary>
        internal static string GDS_GUIDECREATE_T {
            get {
                return ResourceManager.GetString("GDS_GUIDECREATE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Boundary 的當地語系化字串。
        /// </summary>
        internal static string GDS_MARGIN {
            get {
                return ResourceManager.GetString("GDS_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Model Edit 的當地語系化字串。
        /// </summary>
        internal static string GDS_MODELEDIT {
            get {
                return ResourceManager.GetString("GDS_MODELEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Output 的當地語系化字串。
        /// </summary>
        internal static string GDS_OUTPUT {
            get {
                return ResourceManager.GetString("GDS_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Post-processing 的當地語系化字串。
        /// </summary>
        internal static string GDS_POSTPROCESS {
            get {
                return ResourceManager.GetString("GDS_POSTPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Output 的當地語系化字串。
        /// </summary>
        internal static string GDS_SPLINT_CREATION {
            get {
                return ResourceManager.GetString("GDS_SPLINT_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adapt Design 的當地語系化字串。
        /// </summary>
        internal static string GDS_SPLINT_TOOLKIT {
            get {
                return ResourceManager.GetString("GDS_SPLINT_TOOLKIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gender 的當地語系化字串。
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Guide Model 的當地語系化字串。
        /// </summary>
        internal static string GuideModel {
            get {
                return ResourceManager.GetString("GuideModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Guide Type 的當地語系化字串。
        /// </summary>
        internal static string GuideType {
            get {
                return ResourceManager.GetString("GuideType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide password 的當地語系化字串。
        /// </summary>
        internal static string HidePWD {
            get {
                return ResourceManager.GetString("HidePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inlay / Onlay 的當地語系化字串。
        /// </summary>
        internal static string Inlay___Onlay {
            get {
                return ResourceManager.GetString("Inlay / Onlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inlay / Onlay (AI) 的當地語系化字串。
        /// </summary>
        internal static string Inlay___Onlay__AI_ {
            get {
                return ResourceManager.GetString("Inlay / Onlay (AI)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Install 的當地語系化字串。
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last two weeks 的當地語系化字串。
        /// </summary>
        internal static string Last2Week {
            get {
                return ResourceManager.GetString("Last2Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load Project 的當地語系化字串。
        /// </summary>
        internal static string LoadProj {
            get {
                return ResourceManager.GetString("LoadProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load Project 的當地語系化字串。
        /// </summary>
        internal static string LoadProject {
            get {
                return ResourceManager.GetString("LoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Local 的當地語系化字串。
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log in 的當地語系化字串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log out 的當地語系化字串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Male 的當地語系化字串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maximize 的當地語系化字串。
        /// </summary>
        internal static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize 的當地語系化字串。
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Align Model  的當地語系化字串。
        /// </summary>
        internal static string Model_Position {
            get {
                return ResourceManager.GetString("Model_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modified date 的當地語系化字串。
        /// </summary>
        internal static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjacent Tooth 的當地語系化字串。
        /// </summary>
        internal static string Neighbor_Tooth {
            get {
                return ResourceManager.GetString("Neighbor Tooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 None 的當地語系化字串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Note 的當地語系化字串。
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset Coping 的當地語系化字串。
        /// </summary>
        internal static string Offset_Coping {
            get {
                return ResourceManager.GetString("Offset Coping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Manager is already running, do you want to restart Order Manager? 的當地語系化字串。
        /// </summary>
        internal static string OMAlreadyRunning {
            get {
                return ResourceManager.GetString("OMAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open EZCAD 的當地語系化字串。
        /// </summary>
        internal static string Open_EZCAD {
            get {
                return ResourceManager.GetString("Open_EZCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open OrthoAnalysis 的當地語系化字串。
        /// </summary>
        internal static string Open_Ortho {
            get {
                return ResourceManager.GetString("Open_Ortho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open EZCAD.Splint 的當地語系化字串。
        /// </summary>
        internal static string Open_Splint {
            get {
                return ResourceManager.GetString("Open_Splint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open EZCAD.Tray 的當地語系化字串。
        /// </summary>
        internal static string Open_Tray {
            get {
                return ResourceManager.GetString("Open_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Case folder 的當地語系化字串。
        /// </summary>
        internal static string OpenCaseFolder {
            get {
                return ResourceManager.GetString("OpenCaseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Directory 的當地語系化字串。
        /// </summary>
        internal static string OpenDir {
            get {
                return ResourceManager.GetString("OpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order 的當地語系化字串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order ID 的當地語系化字串。
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Information 的當地語系化字串。
        /// </summary>
        internal static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Patient 的當地語系化字串。
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Patient Name 的當地語系化字串。
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Patient Name(Age) 的當地語系化字串。
        /// </summary>
        internal static string PatientNameWithAge {
            get {
                return ResourceManager.GetString("PatientNameWithAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Printing 的當地語系化字串。
        /// </summary>
        internal static string Printing {
            get {
                return ResourceManager.GetString("Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Type 的當地語系化字串。
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Program Path 的當地語系化字串。
        /// </summary>
        internal static string ProgramPath {
            get {
                return ResourceManager.GetString("ProgramPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Provisional Crown 的當地語系化字串。
        /// </summary>
        internal static string Provisional_Crown {
            get {
                return ResourceManager.GetString("Provisional Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Provisional Pontic 的當地語系化字串。
        /// </summary>
        internal static string Provisional_Pontic {
            get {
                return ResourceManager.GetString("Provisional Pontic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reduced Pontic 的當地語系化字串。
        /// </summary>
        internal static string Reduced_Pontic {
            get {
                return ResourceManager.GetString("Reduced Pontic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restore 的當地語系化字串。
        /// </summary>
        internal static string Restore_titlebar {
            get {
                return ResourceManager.GetString("Restore_titlebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Screw Retained Abutment 的當地語系化字串。
        /// </summary>
        internal static string Screw_Retained_Abutment {
            get {
                return ResourceManager.GetString("Screw Retained Abutment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Screw Retained Abutment (Anatomic Crown) 的當地語系化字串。
        /// </summary>
        internal static string Screw_Retained_Abutment__Anatomic_Crown_ {
            get {
                return ResourceManager.GetString("Screw Retained Abutment (Anatomic Crown)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select .exe path 的當地語系化字串。
        /// </summary>
        internal static string SelectPath {
            get {
                return ResourceManager.GetString("SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting 的當地語系化字串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setup Manage 的當地語系化字串。
        /// </summary>
        internal static string SetupManage {
            get {
                return ResourceManager.GetString("SetupManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Software Update 的當地語系化字串。
        /// </summary>
        internal static string SoftwareUpdate {
            get {
                return ResourceManager.GetString("SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Introduction Website 的當地語系化字串。
        /// </summary>
        internal static string SoftwareWeb {
            get {
                return ResourceManager.GetString("SoftwareWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disk space available 的當地語系化字串。
        /// </summary>
        internal static string SpaceAvailable {
            get {
                return ResourceManager.GetString("SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disk space required 的當地語系化字串。
        /// </summary>
        internal static string SpaceRequired {
            get {
                return ResourceManager.GetString("SpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully 的當地語系化字串。
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Surgical guideType 的當地語系化字串。
        /// </summary>
        internal static string SurgicalGT {
            get {
                return ResourceManager.GetString("SurgicalGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Surgical kit 的當地語系化字串。
        /// </summary>
        internal static string SurgicalKit {
            get {
                return ResourceManager.GetString("SurgicalKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Technician 的當地語系化字串。
        /// </summary>
        internal static string Technician {
            get {
                return ResourceManager.GetString("Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Crown Define 的當地語系化字串。
        /// </summary>
        internal static string Teeth_Define {
            get {
                return ResourceManager.GetString("Teeth_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This week 的當地語系化字串。
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Today 的當地語系化字串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Treatment Plan 的當地語系化字串。
        /// </summary>
        internal static string Treatment_Planning {
            get {
                return ResourceManager.GetString("Treatment_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TroubleShooting 的當地語系化字串。
        /// </summary>
        internal static string TroubleShooting {
            get {
                return ResourceManager.GetString("TroubleShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uninstall 的當地語系化字串。
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Veneer 的當地語系化字串。
        /// </summary>
        internal static string Veneer {
            get {
                return ResourceManager.GetString("Veneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show password 的當地語系化字串。
        /// </summary>
        internal static string ViewPWD {
            get {
                return ResourceManager.GetString("ViewPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workflow 的當地語系化字串。
        /// </summary>
        internal static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
    }
}
